import { useRef, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { createFreeAiProject, createPaidAiDraft, createAiCheckout } from "../api/aiTattooApi";
import { PLACEMENTS, TATTOO_STYLES } from "../data/tattooOptions";

function Selector({title,items,value,onChange,trackRef}){const move=d=>{const el=trackRef.current;if(!el)return;const card=el.querySelector(".visual-carousel-card");if(card)el.scrollBy({left:d*(card.getBoundingClientRect().width+12)*3,behavior:"smooth"});};return <section className="section carousel-section"><div className="selection-section-head"><div><p className="subtitle">Locked after generation</p><h2>{title}</h2></div><span className="selection-value">{value||"Choose one"}</span></div><div className="selector-carousel-shell"><button className="carousel-arrow carousel-arrow-left" onClick={()=>move(-1)} type="button">‹</button><div className="selector-carousel-track" ref={trackRef}>{items.map(x=><button type="button" key={x.value} className={`visual-carousel-card ${value===x.value?"visual-option-selected":""}`} onClick={()=>onChange(x.value)}><img src={x.image} alt=""/><span>{x.value}</span></button>)}</div><button className="carousel-arrow carousel-arrow-right" onClick={()=>move(1)} type="button">›</button></div></section>}
function CreateAiTattooPage(){const nav=useNavigate();const [params]=useSearchParams();const paid=params.get("paid")==="1";const pRef=useRef(null),sRef=useRef(null);const [form,setForm]=useState({title:"",tattooStyle:"",placement:"",description:""});const [file,setFile]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const submit=async e=>{e.preventDefault();setError("");if(!form.tattooStyle||!form.placement)return setError("Choose a tattoo style and placement.");setBusy(true);try{if(paid){const p=await createPaidAiDraft(form,file);const checkout=await createAiCheckout(p.id);window.location.assign(checkout.url);}else{const p=await createFreeAiProject(form,file);nav(`/ai-studio/${p.id}`);}}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <main className="page-shell"><section className="container ai-create-shell"><div className="header"><p className="subtitle">{paid?"Premium tattoo project":"Your free tattoo project"}</p><h1>Build the creative direction.</h1><p>Style and placement become permanent after the project is created. Improvements stay focused on this tattoo.</p></div><form onSubmit={submit} className="ai-create-form"><div className="card form-card"><div className="form-row"><label>Project name<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required placeholder="Wolf forearm concept"/></label><label>Initial reference (optional)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><label>Describe the tattoo<textarea rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required placeholder="Describe the subject, mood, composition, important details and colors..."/></label></div><Selector title="Body placement" items={PLACEMENTS} value={form.placement} onChange={v=>setForm({...form,placement:v})} trackRef={pRef}/><Selector title="Tattoo style" items={TATTOO_STYLES} value={form.tattooStyle} onChange={v=>setForm({...form,tattooStyle:v})} trackRef={sRef}/>{error&&<p className="error-message">{error}</p>}<button className="primary-button ai-generate-button" disabled={busy}>{busy?"Creating your tattoo concept...":paid?"Continue to secure payment":"Generate free concept"}</button></form></section></main>}
export default CreateAiTattooPage;
