import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getMyTattooRequests } from "../api/tattooRequestApi";
import { readResponse } from "../api/http";
import { formatDate, formatDateTime, formatTime, getEntityId, getStatusClass, getStatusName } from "../utils/format";

function MyTattooRequestsPage() {
  const [requests, setRequests] = useState([]);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  useEffect(()=>{ loadRequests(); }, []);
  async function loadRequests(){ try{ const response=await getMyTattooRequests(); const data=await readResponse(response); if(!response.ok){setError(typeof data==="string"?data:JSON.stringify(data));return;} setRequests(data);}catch{setError("Server connection failed. Please try again.");}finally{setIsLoading(false);} }
  return <main className="page-shell"><section className="container"><div className="header"><p className="subtitle">My Tattoo Requests</p><h1>Track your tattoo ideas</h1><p>View statuses, artist responses, consultation details, and tattoo sessions.</p></div>{isLoading&&<p className="message">Loading tattoo requests...</p>}{error&&<p className="error">{error}</p>}{!isLoading&&!error&&requests.length===0&&<p className="message">You have not created any tattoo requests yet.</p>}<div className="grid-2">{requests.map((request,index)=>{const id=getEntityId(request,index); return <article className="card artist-card" key={index}><div className="card-head"><div><p className="subtitle inline-subtitle">Request #{id}</p><h2>{request.placement || "Tattoo request"}</h2></div><span className={`status-pill ${getStatusClass(request.status)}`}>{getStatusName(request.status)}</span></div><p className="muted">{request.description}</p><div className="info-list"><p><span>Created:</span> {formatDate(request.createdOn)}</p><p><span>Artist ID:</span> {request.tattooArtistId}</p></div>{request.images?.length>0&&<div className="section"><h3>Reference images</h3><div className="image-grid">{request.images.slice(0,4).map((img,i)=><img key={i} src={img.imageUrl} alt="Reference" />)}</div></div>}{request.artistResponse&&<div className="section highlighted"><h3>Artist response</h3><p className="muted">{request.artistResponse.responseMessage}</p><div className="small-list-row"><span>{request.artistResponse.estimatedPrice} BGN</span><span>{request.artistResponse.estimatedHours} hours</span><span>{formatDate(request.artistResponse.createdOn)}</span></div></div>}{request.consultation&&<div className="section"><h3>Consultation</h3><div className="info-list"><p><span>Start:</span> {formatDateTime(request.consultation.startTime)}</p><p><span>End:</span> {formatDateTime(request.consultation.endTime)}</p><p><span>Notes:</span> {request.consultation.notes || "No notes"}</p></div></div>}{request.tattooSessions?.length>0&&<div className="section"><h3>Tattoo sessions</h3><div className="small-list">{request.tattooSessions.map((s,i)=><div className="small-list-row" key={i}><span>Session {i+1}</span><span>{formatDateTime(s.startTime)} - {formatTime(s.endTime)}</span><span>{s.priceForTheSession} BGN</span></div>)}</div></div>}<div className="action-row"><Link className="secondary-button" to={`/book-consultation/${id}`}>Book consultation</Link><Link className="primary-button" to={`/book-session/${id}`}>Book session</Link></div></article>})}</div><p className="muted backend-note">If request IDs are missing from backend DTOs, actions use a fallback. Add Id to GetTattooRequestDto for reliable action buttons.</p></section></main>;
}
export default MyTattooRequestsPage;
