// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tattoo_Project.Data;

#nullable disable

namespace Tattoo_Project.Migrations
{
    [DbContext(typeof(TattooDbContext))]
    [Migration("20260612131536_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tattoo_Project.Models.ArtistRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TattooArtistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TattooArtistId");

                    b.ToTable("ArtistRequirement");
                });

            modelBuilder.Entity("Tattoo_Project.Models.ArtistResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TattooRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TattooRequestId")
                        .IsUnique();

                    b.ToTable("ArtistResponses");
                });

            modelBuilder.Entity("Tattoo_Project.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Tattoo_Project.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TattooRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TattooRequestId")
                        .IsUnique();

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("Tattoo_Project.Models.PortfolioImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TattooArtistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TattooArtistId");

                    b.ToTable("PortfolioImage");
                });

            modelBuilder.Entity("Tattoo_Project.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TattooArtistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TattooArtistId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Tattoo_Project.Models.TattooArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("OffersOnlineConsultation")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresDeposit")
                        .HasColumnType("bit");

                    b.Property<string>("StudioAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StudioName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TattooArtists");
                });

            modelBuilder.Entity("Tattoo_Project.Models.TattooReferenceImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TattooRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TattooRequestId");

                    b.ToTable("TattooReferenceImages");
                });

            modelBuilder.Entity("Tattoo_Project.Models.TattooRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RemainingSessionsToBook")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TattooArtistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TattooArtistId");

                    b.ToTable("TattooRequests");
                });

            modelBuilder.Entity("Tattoo_Project.Models.TattooSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TattooRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TattooRequestId");

                    b.ToTable("TattooSessions");
                });

            modelBuilder.Entity("Tattoo_Project.Models.ArtistRequirement", b =>
                {
                    b.HasOne("Tattoo_Project.Models.TattooArtist", "TattooArtist")
                        .WithMany("Requirements")
                        .HasForeignKey("TattooArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TattooArtist");
                });

            modelBuilder.Entity("Tattoo_Project.Models.ArtistResponse", b =>
                {
                    b.HasOne("Tattoo_Project.Models.TattooRequest", "TattooRequest")
                        .WithOne("ArtistResponse")
                        .HasForeignKey("Tattoo_Project.Models.ArtistResponse", "TattooRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TattooRequest");
                });

            modelBuilder.Entity("Tattoo_Project.Models.Consultation", b =>
                {
                    b.HasOne("Tattoo_Project.Models.TattooRequest", "TattooRequest")
                        .WithOne("Consultation")
                        .HasForeignKey("Tattoo_Project.Models.Consultation", "TattooRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TattooRequest");
                });

            modelBuilder.Entity("Tattoo_Project.Models.PortfolioImage", b =>
                {
                    b.HasOne("Tattoo_Project.Models.TattooArtist", "TattooArtist")
                        .WithMany("PortfolioImages")
                        .HasForeignKey("TattooArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TattooArtist");
                });

            modelBuilder.Entity("Tattoo_Project.Models.Schedule", b =>
                {
                    b.HasOne("Tattoo_Project.Models.TattooArtist", "TattooArtist")
                        .WithMany("Schedules")
                        .HasForeignKey("TattooArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TattooArtist");
                });

            modelBuilder.Entity("Tattoo_Project.Models.TattooReferenceImage", b =>
                {
                    b.HasOne("Tattoo_Project.Models.TattooRequest", "TattooRequest")
                        .WithMany("Images")
                        .HasForeignKey("TattooRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TattooRequest");
                });

            modelBuilder.Entity("Tattoo_Project.Models.TattooRequest", b =>
                {
                    b.HasOne("Tattoo_Project.Models.Client", "Client")
                        .WithMany("TattooRequests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tattoo_Project.Models.TattooArtist", "TattooArtist")
                        .WithMany("TattooRequests")
                        .HasForeignKey("TattooArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("TattooArtist");
                });

            modelBuilder.Entity("Tattoo_Project.Models.TattooSession", b =>
                {
                    b.HasOne("Tattoo_Project.Models.TattooRequest", "TattooRequest")
                        .WithMany("TattooSessions")
                        .HasForeignKey("TattooRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TattooRequest");
                });

            modelBuilder.Entity("Tattoo_Project.Models.Client", b =>
                {
                    b.Navigation("TattooRequests");
                });

            modelBuilder.Entity("Tattoo_Project.Models.TattooArtist", b =>
                {
                    b.Navigation("PortfolioImages");

                    b.Navigation("Requirements");

                    b.Navigation("Schedules");

                    b.Navigation("TattooRequests");
                });

            modelBuilder.Entity("Tattoo_Project.Models.TattooRequest", b =>
                {
                    b.Navigation("ArtistResponse");

                    b.Navigation("Consultation");

                    b.Navigation("Images");

                    b.Navigation("TattooSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
