const en = {
  heroTitle: "Turn client messages into a clear tattoo workflow.",
  heroBody: "From the first request to the finished tattoo, InkRoute keeps every decision, appointment and session in one organized process.",
  heroDetail: "Send clients one link, receive the details you need and let them book only from times you are actually available.",
  outcomesEyebrow: "From scattered messages to a clear process",
  outcomesTitle: "You stay in control. InkRoute handles the organization.",
  outcomes: [
    ["Clear requests from the start", "Placement, style, description and references arrive together — not across dozens of messages."],
    ["You decide what happens next", "Choose consultation first or move a clear project directly to planned sessions."],
    ["Clients book without the back-and-forth", "They choose only from real times that match the consultation or session you defined."],
  ],
  setupTitle: "Set it up once. Use it for every new tattoo request.",
  setupIntro: "Create your account, confirm it with the six-digit email code, build your artist profile, create or join a studio, set your schedule and share your permanent link.",
  setupProfileTitle: "A profile that answers the first questions before the first chat",
  profileItems:["Name, photo, description and portfolio","Up to eight specialty styles","Studio, location and client requirements","Consultation duration and online availability","Optional phone visibility; email always private","Deposit information shown without InkRoute collecting it"],
  profileNote:"Your profile becomes public after it is connected to a studio. Your personal link stays the same even if your name or studio changes.",
  scheduleCardTitle:"A schedule clients can book — without seeing your private calendar",
  scheduleItems:["Separate hours for consultations and tattoo sessions","Different hours by day and multiple intervals in one day","Days off, absence periods and specific hourly breaks","Booked, past, unavailable and insufficient time slots excluded automatically"],
  scheduleNote:"Clients see only times that are actually long enough and available for the step you defined.",
  offerEyebrow:"Start with your real clients",offerTitle:"Bring your next tattoo request into one clear process.",offerItems:["Receive the essential project details together","Choose consultation or direct sessions","Let clients book from real free times","Keep appointments connected to the project","Share one permanent public profile link","Add sessions and complete the project"],
  finalTitle: "Spend less time organizing. Keep more time for tattooing.",
  finalBody: "Create your InkRoute profile, share one link with your clients and manage every project through one clear process.",
};

const bg = {
  heroTitle: "Превърни съобщенията от клиенти в ясен процес за всеки татус.",
  heroBody: "От първото запитване до завършения татус InkRoute събира решенията, резервациите и сесиите в един подреден процес.",
  heroDetail: "Изпрати на клиентите един линк, получи нужната информация и им позволи да запазват само часове, в които наистина си свободен.",
  outcomesEyebrow: "От разпилени съобщения към ясен процес",
  outcomesTitle: "Ти контролираш проекта. InkRoute подрежда организацията.",
  outcomes: [
    ["Ясно запитване още в началото", "Мястото, стилът, описанието и референтните изображения пристигат заедно — не в десетки съобщения."],
    ["Ти решаваш какво следва", "Избери първо консултация или насочи ясния проект директно към планираните сесии."],
    ["Клиентите запазват час без излишен чат", "Те избират само от реално свободните часове за определената от теб консултация или сесия."],
  ],
  setupTitle: "Настрой го веднъж. Използвай го за всяко ново запитване.",
  setupIntro: "Създай акаунт, потвърди го с шестцифрения код от имейла, направи профил на татуист, създай или се присъедини към студио, настрой графика и сподели постоянния си линк.",
  setupProfileTitle: "Профил, който отговаря на първите въпроси още преди първия чат",
  profileItems:["Име, снимка, описание и портфолио","До осем специализирани стила","Студио, локация и изисквания към клиентите","Продължителност и възможност за онлайн консултация","Телефонът се показва по избор; имейлът остава личен","Информация за депозит, без InkRoute да го събира"],
  profileNote:"Профилът става публичен след свързване със студио. Личният ти линк остава същият дори ако промениш името или студиото си.",
  scheduleCardTitle:"График, от който клиентите запазват час — без да виждат личния ти календар",
  scheduleItems:["Отделни часове за консултации и тату сесии","Различни часове по дни и няколко интервала в един ден","Почивни дни, периоди на отсъствие и часови почивки","Автоматично изключване на заети, минали, недостъпни и прекалено кратки интервали"],
  scheduleNote:"Клиентите виждат само часовете, които реално са свободни и достатъчно дълги за определената от теб стъпка.",
  offerEyebrow:"Започни с реалните си клиенти",offerTitle:"Подреди следващото си запитване в един ясен процес.",offerItems:["Получи важната информация за проекта на едно място","Избери консултация или директни сесии","Остави клиента да избере от реално свободните часове","Запази резервациите свързани с проекта","Сподели един постоянен публичен линк","Добавяй сесии и завърши проекта"],
  finalTitle: "По-малко време за организация. Повече време за татуиране.",
  finalBody: "Създай профила си в InkRoute, сподели един линк с клиентите си и управлявай всеки проект чрез ясен процес.",
};

const de = {
  heroTitle:"Mach aus Kundennachrichten einen klaren Tattoo-Ablauf.",heroBody:"Von der ersten Anfrage bis zum fertigen Tattoo hält InkRoute Entscheidungen, Termine und Sitzungen in einem organisierten Prozess zusammen.",
  heroDetail: "Sende Kunden einen Link, erhalte alle nötigen Angaben und lass sie nur Zeiten buchen, zu denen du wirklich frei bist.",
  outcomesEyebrow: "Von verstreuten Nachrichten zu einem klaren Ablauf", outcomesTitle: "Du behältst die Kontrolle. InkRoute übernimmt die Organisation.",
  outcomes: [["Klare Anfragen von Anfang an","Körperstelle, Stil, Beschreibung und Referenzen kommen zusammen an – nicht in Dutzenden Nachrichten."],["Du bestimmst den nächsten Schritt","Wähle zuerst eine Beratung oder führe ein klares Projekt direkt zu geplanten Sitzungen."],["Kunden buchen ohne Hin und Her","Sie wählen nur wirklich freie Zeiten für die von dir festgelegte Beratung oder Sitzung."]],
  setupTitle:"Einmal einrichten. Für jede neue Tattoo-Anfrage nutzen.",setupIntro:"Konto erstellen und bestätigen, Tätowiererprofil einrichten, Studio erstellen oder beitreten, Zeitplan festlegen und den dauerhaften Link teilen.",setupProfileTitle:"Ein Profil, das erste Fragen schon vor dem ersten Chat beantwortet",profileItems:["Name, Foto, Beschreibung und Portfolio","Bis zu acht Spezialstile","Studio, Standort und Kundenanforderungen","Beratungsdauer und Online-Beratung","Telefon optional sichtbar; E-Mail immer privat","Kautionsinfo, ohne Einzug durch InkRoute"],profileNote:"Das Profil wird nach der Studioverbindung öffentlich. Dein Link bleibt auch bei Namens- oder Studiowechsel gleich.",scheduleCardTitle:"Ein buchbarer Zeitplan – ohne deinen privaten Kalender zu zeigen",scheduleItems:["Getrennte Zeiten für Beratungen und Sitzungen","Unterschiedliche Zeiten und mehrere Intervalle pro Tag","Freie Tage, Abwesenheiten und Stundenpausen","Gebuchte, vergangene, gesperrte und zu kurze Zeiten automatisch ausgeschlossen"],scheduleNote:"Kunden sehen nur wirklich freie und ausreichend lange Termine.",offerEyebrow:"Starte mit echten Kunden",offerTitle:"Bring deine nächste Tattoo-Anfrage in einen klaren Ablauf.",offerItems:["Wichtige Projektdaten zusammen erhalten","Beratung oder direkte Sitzungen wählen","Kunden aus echten freien Zeiten buchen lassen","Termine mit dem Projekt verbunden halten","Einen dauerhaften öffentlichen Link teilen","Sitzungen ergänzen und Projekt abschließen"],finalTitle:"Weniger organisieren. Mehr Zeit fürs Tätowieren.",finalBody:"Erstelle dein InkRoute-Profil, teile einen Link mit deinen Kunden und verwalte jedes Projekt in einem klaren Ablauf.",
};

const fr = {
  heroTitle:"Transformez les messages de vos clients en un processus de tatouage clair.",heroBody:"De la première demande au tatouage terminé, InkRoute réunit décisions, rendez-vous et séances dans un seul processus organisé.",
  heroDetail: "Envoyez un seul lien, recevez les informations nécessaires et laissez vos clients réserver uniquement vos vrais créneaux libres.",
  outcomesEyebrow:"Des messages dispersés à un processus clair",outcomesTitle:"Vous gardez le contrôle. InkRoute organise le reste.",outcomes:[["Des demandes claires dès le départ","Emplacement, style, description et références arrivent ensemble, pas dans des dizaines de messages."],["Vous décidez de la suite","Choisissez une consultation ou passez directement aux séances pour un projet déjà clair."],["Les clients réservent sans échanges inutiles","Ils choisissent uniquement les créneaux réellement libres pour la consultation ou la séance définie."]],
  setupTitle:"Configurez-le une fois. Utilisez-le pour chaque nouvelle demande.",setupIntro:"Créez et confirmez votre compte, préparez votre profil, créez ou rejoignez un studio, réglez le planning et partagez votre lien permanent.",setupProfileTitle:"Un profil qui répond aux premières questions avant le premier échange",profileItems:["Nom, photo, description et portfolio","Jusqu’à huit styles spécialisés","Studio, localisation et exigences","Durée et consultation en ligne","Téléphone visible au choix; e-mail privé","Acompte affiché sans encaissement par InkRoute"],profileNote:"Le profil devient public après son rattachement à un studio. Le lien reste identique si votre nom ou studio change.",scheduleCardTitle:"Un planning réservable sans montrer votre calendrier privé",scheduleItems:["Horaires séparés pour consultations et séances","Horaires variables et plusieurs plages par jour","Jours libres, absences et pauses horaires","Créneaux réservés, passés, indisponibles ou trop courts automatiquement exclus"],scheduleNote:"Les clients voient seulement les créneaux vraiment libres et assez longs.",offerEyebrow:"Commencez avec vos vrais clients",offerTitle:"Organisez votre prochaine demande dans un processus clair.",offerItems:["Recevoir ensemble les informations essentielles","Choisir consultation ou séances directes","Laisser les clients choisir de vrais créneaux libres","Garder les rendez-vous liés au projet","Partager un lien public permanent","Ajouter des séances et terminer le projet"],finalTitle:"Moins de temps à organiser. Plus de temps à tatouer.",finalBody:"Créez votre profil InkRoute, partagez un lien avec vos clients et gérez chaque projet dans un processus clair.",
};

const es = {
  heroTitle:"Convierte los mensajes de clientes en un proceso de tatuaje claro.",heroBody:"Desde la primera solicitud hasta el tatuaje terminado, InkRoute reúne decisiones, citas y sesiones en un único proceso organizado.",
  heroDetail:"Envía un solo enlace, recibe la información necesaria y deja que tus clientes reserven únicamente cuando realmente estás disponible.",
  outcomesEyebrow:"De mensajes dispersos a un proceso claro",outcomesTitle:"Tú mantienes el control. InkRoute organiza el resto.",outcomes:[["Solicitudes claras desde el principio","Zona, estilo, descripción y referencias llegan juntas, no en decenas de mensajes."],["Tú decides el siguiente paso","Elige primero una consulta o lleva un proyecto claro directamente a las sesiones."],["Los clientes reservan sin mensajes innecesarios","Solo eligen horas realmente libres para la consulta o sesión que has definido."]],
  setupTitle:"Configúralo una vez. Úsalo para cada nueva solicitud.",setupIntro:"Crea y confirma la cuenta, prepara tu perfil, crea o únete a un estudio, configura el horario y comparte tu enlace permanente.",setupProfileTitle:"Un perfil que responde las primeras preguntas antes del primer chat",profileItems:["Nombre, foto, descripción y portfolio","Hasta ocho estilos especializados","Estudio, ubicación y requisitos","Duración y consulta online","Teléfono visible opcional; correo privado","Depósito mostrado sin que InkRoute lo cobre"],profileNote:"El perfil se hace público al conectarlo con un estudio. El enlace no cambia aunque cambies tu nombre o estudio.",scheduleCardTitle:"Un horario reservable sin mostrar tu calendario privado",scheduleItems:["Horas separadas para consultas y sesiones","Horarios diferentes y varios intervalos al día","Días libres, ausencias y pausas horarias","Horas reservadas, pasadas, bloqueadas o demasiado cortas excluidas automáticamente"],scheduleNote:"Los clientes solo ven horas realmente libres y suficientemente largas.",offerEyebrow:"Empieza con clientes reales",offerTitle:"Organiza tu próxima solicitud en un proceso claro.",offerItems:["Recibir juntos los datos esenciales","Elegir consulta o sesiones directas","Dejar que el cliente elija horas realmente libres","Mantener las citas unidas al proyecto","Compartir un enlace público permanente","Añadir sesiones y completar el proyecto"],finalTitle:"Menos tiempo organizando. Más tiempo tatuando.",finalBody:"Crea tu perfil de InkRoute, comparte un enlace con tus clientes y gestiona cada proyecto mediante un proceso claro.",
};

const it = {
  heroTitle:"Trasforma i messaggi dei clienti in un processo chiaro per ogni tatuaggio.",heroBody:"Dalla prima richiesta al tatuaggio finito, InkRoute riunisce decisioni, appuntamenti e sessioni in un unico processo organizzato.",
  heroDetail:"Invia un solo link, ricevi le informazioni necessarie e lascia che i clienti prenotino solo quando sei davvero disponibile.",
  outcomesEyebrow:"Da messaggi sparsi a un processo chiaro",outcomesTitle:"Tu mantieni il controllo. InkRoute organizza il resto.",outcomes:[["Richieste chiare fin dall’inizio","Posizione, stile, descrizione e riferimenti arrivano insieme, non in decine di messaggi."],["Decidi tu il passo successivo","Scegli prima una consulenza oppure porta un progetto chiaro direttamente alle sessioni."],["I clienti prenotano senza messaggi inutili","Scelgono solo gli orari realmente liberi per la consulenza o sessione che hai definito."]],
  setupTitle:"Configuralo una volta. Usalo per ogni nuova richiesta.",setupIntro:"Crea e conferma l’account, prepara il profilo, crea o unisciti a uno studio, imposta gli orari e condividi il link permanente.",setupProfileTitle:"Un profilo che risponde alle prime domande prima della prima chat",profileItems:["Nome, foto, descrizione e portfolio","Fino a otto stili specializzati","Studio, posizione e requisiti","Durata e consulenza online","Telefono visibile a scelta; e-mail privata","Deposito mostrato senza incasso da InkRoute"],profileNote:"Il profilo diventa pubblico dopo il collegamento a uno studio. Il link resta uguale anche se cambiano nome o studio.",scheduleCardTitle:"Un orario prenotabile senza mostrare il calendario privato",scheduleItems:["Orari separati per consulenze e sessioni","Orari diversi e più intervalli al giorno","Giorni liberi, assenze e pause orarie","Orari prenotati, passati, bloccati o troppo brevi esclusi automaticamente"],scheduleNote:"I clienti vedono solo orari davvero liberi e abbastanza lunghi.",offerEyebrow:"Inizia con clienti reali",offerTitle:"Organizza la prossima richiesta in un processo chiaro.",offerItems:["Ricevere insieme i dati essenziali","Scegliere consulenza o sessioni dirette","Far scegliere solo orari davvero liberi","Tenere gli appuntamenti collegati al progetto","Condividere un link pubblico permanente","Aggiungere sessioni e completare il progetto"],finalTitle:"Meno tempo a organizzare. Più tempo per tatuare.",finalBody:"Crea il tuo profilo InkRoute, condividi un link con i clienti e gestisci ogni progetto con un processo chiaro.",
};

export const landingSalesCopy = { en, bg, de, fr, es, it };
