const faq = {
  en:[
    ["Is InkRoute free for clients?","Yes. Clients can send requests, book appointments and follow projects completely free."],
    ["What do artists receive in the first three months?","Tattoo artists use the complete InkRoute process free for the first three months."],
    ["Do I need to belong to a studio?","Your profile becomes public after connecting to a studio. You can create one or request to join one."],
    ["Can I continue without a consultation?","Yes. You decide whether the client books a consultation or moves directly to sessions."],
    ["How are sessions booked?","You define each price and duration. The client books every session separately from your real availability."],
    ["Can bookings overlap?","No. Bookings, time off, past times and gaps that are too short are automatically excluded."],
    ["What appears on my public profile?","Name, photo, studio, location, styles, portfolio, description and requirements. You choose whether your phone number is visible; your email stays private."],
    ["Does InkRoute collect deposits?","No. You can show whether a deposit is required and its amount, but InkRoute does not collect it."],
  ],
  bg:[
    ["InkRoute безплатен ли е за клиентите?","Да. Клиентите изпращат запитвания, запазват часове и следят проектите си напълно безплатно."],
    ["Какво получават татуистите през първите три месеца?","Татуистите използват безплатно целия процес в InkRoute през първите три месеца."],
    ["Трябва ли да съм част от студио?","Профилът става публичен след свързване със студио. Можеш да създадеш свое или да поискаш присъединяване."],
    ["Мога ли да продължа без консултация?","Да. Ти решаваш дали клиентът първо да запази консултация, или да премине директно към сесиите."],
    ["Как се запазват сесиите?","Ти определяш цена и продължителност. Клиентът запазва всяка сесия отделно от реално свободните ти часове."],
    ["Могат ли резервациите да се застъпят?","Не. Заетите часове, почивките, миналите часове и кратките интервали се изключват автоматично."],
    ["Какво се показва в публичния ми профил?","Име, снимка, студио, локация, стилове, портфолио, описание и изисквания. Ти избираш дали телефонът ти да се вижда; имейлът остава личен."],
    ["InkRoute събира ли депозитите?","Не. Можеш да покажеш дали изискваш депозит и размера му, но InkRoute не го събира."],
  ],
  de:[
    ["Ist InkRoute für Kunden kostenlos?","Ja. Kunden können Anfragen senden, Termine buchen und Projekte kostenlos verfolgen."],
    ["Was erhalten Tätowierer in den ersten drei Monaten?","Sie nutzen den gesamten InkRoute-Ablauf in den ersten drei Monaten kostenlos."],
    ["Muss ich zu einem Studio gehören?","Dein Profil wird nach der Verbindung mit einem Studio öffentlich. Du kannst eines erstellen oder beitreten."],
    ["Kann ich ohne Beratung fortfahren?","Ja. Du entscheidest zwischen Beratung und direkter Planung der Sitzungen."],
    ["Wie werden Sitzungen gebucht?","Du legst Preis und Dauer fest. Der Kunde bucht jede Sitzung aus deinen freien Zeiten."],
    ["Können sich Buchungen überschneiden?","Nein. Buchungen, Auszeiten, vergangene Termine und zu kurze Lücken werden ausgeschlossen."],
    ["Was zeigt mein öffentliches Profil?","Name, Foto, Studio, Standort, Stile, Portfolio, Beschreibung und Anforderungen. Du entscheidest, ob deine Telefonnummer sichtbar ist; deine E-Mail bleibt privat."],
    ["Zieht InkRoute Kautionen ein?","Nein. Anforderung und Betrag können angezeigt werden, aber InkRoute zieht sie nicht ein."],
  ],
  fr:[
    ["InkRoute est-il gratuit pour les clients ?","Oui. Les clients envoient des demandes, réservent et suivent leurs projets gratuitement."],
    ["Que reçoivent les tatoueurs pendant trois mois ?","Ils utilisent gratuitement tout le processus InkRoute pendant les trois premiers mois."],
    ["Dois-je appartenir à un studio ?","Le profil devient public après son rattachement à un studio. Vous pouvez en créer ou en rejoindre un."],
    ["Puis-je continuer sans consultation ?","Oui. Vous choisissez entre une consultation et un passage direct aux séances."],
    ["Comment les séances sont-elles réservées ?","Vous définissez prix et durée. Le client réserve chaque séance dans vos disponibilités."],
    ["Les réservations peuvent-elles se chevaucher ?","Non. Réservations, absences, heures passées et intervalles trop courts sont exclus."],
    ["Que montre mon profil public ?","Nom, photo, studio, localisation, styles, portfolio, description et exigences. Vous choisissez si votre téléphone est visible ; votre e-mail reste privé."],
    ["InkRoute encaisse-t-il les acomptes ?","Non. L’exigence et le montant peuvent être affichés, mais InkRoute ne les encaisse pas."],
  ],
  es:[
    ["¿InkRoute es gratis para clientes?","Sí. Los clientes envían solicitudes, reservan y siguen sus proyectos gratis."],
    ["¿Qué reciben los tatuadores durante tres meses?","Usan todo el proceso de InkRoute gratis durante los primeros tres meses."],
    ["¿Tengo que pertenecer a un estudio?","El perfil se hace público al conectarse a un estudio. Puedes crear uno o solicitar unirte."],
    ["¿Puedo continuar sin consulta?","Sí. Tú eliges entre consulta y pasar directamente a las sesiones."],
    ["¿Cómo se reservan las sesiones?","Defines precio y duración. El cliente reserva cada sesión entre tus horas libres."],
    ["¿Pueden solaparse las reservas?","No. Reservas, descansos, horas pasadas e intervalos demasiado cortos se excluyen."],
    ["¿Qué muestra mi perfil público?","Nombre, foto, estudio, ubicación, estilos, portfolio, descripción y requisitos. Tú eliges si se muestra tu teléfono; tu correo sigue siendo privado."],
    ["¿InkRoute cobra los depósitos?","No. Puedes mostrar el requisito y el importe, pero InkRoute no lo cobra."],
  ],
  it:[
    ["InkRoute è gratuito per i clienti?","Sì. I clienti inviano richieste, prenotano e seguono i progetti gratuitamente."],
    ["Cosa ricevono i tatuatori nei primi tre mesi?","Usano gratuitamente l’intero processo InkRoute per i primi tre mesi."],
    ["Devo appartenere a uno studio?","Il profilo diventa pubblico quando è collegato a uno studio. Puoi crearne uno o chiedere di unirti."],
    ["Posso continuare senza consulenza?","Sì. Scegli tu tra consulenza e passaggio diretto alle sessioni."],
    ["Come vengono prenotate le sessioni?","Definisci prezzo e durata. Il cliente prenota ogni sessione nei tuoi orari liberi."],
    ["Le prenotazioni possono sovrapporsi?","No. Prenotazioni, pause, orari passati e intervalli troppo brevi vengono esclusi."],
    ["Cosa mostra il mio profilo pubblico?","Nome, foto, studio, posizione, stili, portfolio, descrizione e requisiti. Scegli tu se mostrare il telefono; l’e-mail resta privata."],
    ["InkRoute incassa i depositi?","No. Puoi mostrare requisito e importo, ma InkRoute non li incassa."],
  ],
};

export function getLandingFaq(language) { return faq[language] || faq.en; }
