export const publicLinkTranslations = {
  bg: {
    "Send your idea directly to": "Изпрати идеята си директно на",
    "Your public link": "Твоят публичен линк", "Receive requests directly": "Получавай заявки директно",
    "Send this link to a client or add it to your bio to receive structured requests directly in InkRoute.": "Изпрати този линк на клиент или го добави в биото си, за да получаваш структурирани заявки директно в InkRoute.",
    "Copy link": "Копирай линка", "Share": "Сподели", "Link copied": "Линкът е копиран",
    "Tattoo artist": "Татуист", "Send request": "Изпрати запитване", "About the artist": "За татуиста",
    "Important information": "Важна информация", "Selected work": "Подбрани творби", "Before you send a request": "Преди да изпратиш запитване",
    "Artist requirements": "Изисквания на татуиста", "Start your tattoo project": "Започни своя тату проект",
    "Artist profile unavailable": "Профилът на татуиста не е достъпен", "This artist profile could not be found.": "Този профил на татуист не беше намерен.",
    "Explore studios": "Разгледай студиа", "Loading artist profile...": "Зареждане на профила...",
    "InkRoute will keep your request, consultation and tattoo sessions organized in one place.": "InkRoute ще организира запитването, консултацията и тату сесиите ти на едно място."
  },
  de: {
    "Send your idea directly to": "Sende deine Idee direkt an",
    "Your public link": "Dein öffentlicher Link", "Receive requests directly": "Anfragen direkt erhalten", "Send this link to a client or add it to your bio to receive structured requests directly in InkRoute.": "Sende diesen Link an Kunden oder füge ihn deiner Bio hinzu, um strukturierte Anfragen direkt in InkRoute zu erhalten.", "Copy link": "Link kopieren", "Share": "Teilen", "Link copied": "Link kopiert", "Tattoo artist": "Tätowierer", "Send request": "Anfrage senden", "About the artist": "Über den Künstler", "Important information": "Wichtige Informationen", "Selected work": "Ausgewählte Arbeiten", "Before you send a request": "Vor deiner Anfrage", "Artist requirements": "Anforderungen des Künstlers", "Start your tattoo project": "Starte dein Tattoo-Projekt", "Artist profile unavailable": "Künstlerprofil nicht verfügbar", "This artist profile could not be found.": "Dieses Künstlerprofil wurde nicht gefunden.", "Explore studios": "Studios entdecken", "Loading artist profile...": "Künstlerprofil wird geladen...", "InkRoute will keep your request, consultation and tattoo sessions organized in one place.": "InkRoute organisiert deine Anfrage, Beratung und Tattoo-Sitzungen an einem Ort."
  },
  fr: {
    "Send your idea directly to": "Envoyez votre idée directement à",
    "Your public link": "Votre lien public", "Receive requests directly": "Recevez des demandes directement", "Send this link to a client or add it to your bio to receive structured requests directly in InkRoute.": "Envoyez ce lien à un client ou ajoutez-le à votre bio pour recevoir des demandes structurées directement dans InkRoute.", "Copy link": "Copier le lien", "Share": "Partager", "Link copied": "Lien copié", "Tattoo artist": "Tatoueur", "Send request": "Envoyer une demande", "About the artist": "À propos de l’artiste", "Important information": "Informations importantes", "Selected work": "Œuvres sélectionnées", "Before you send a request": "Avant d’envoyer une demande", "Artist requirements": "Exigences de l’artiste", "Start your tattoo project": "Commencez votre projet de tatouage", "Artist profile unavailable": "Profil indisponible", "This artist profile could not be found.": "Ce profil de tatoueur est introuvable.", "Explore studios": "Découvrir les studios", "Loading artist profile...": "Chargement du profil...", "InkRoute will keep your request, consultation and tattoo sessions organized in one place.": "InkRoute organise votre demande, consultation et séances de tatouage au même endroit."
  },
  es: {
    "Send your idea directly to": "Envía tu idea directamente a",
    "Your public link": "Tu enlace público", "Receive requests directly": "Recibe solicitudes directamente", "Send this link to a client or add it to your bio to receive structured requests directly in InkRoute.": "Envía este enlace a un cliente o añádelo a tu biografía para recibir solicitudes estructuradas directamente en InkRoute.", "Copy link": "Copiar enlace", "Share": "Compartir", "Link copied": "Enlace copiado", "Tattoo artist": "Tatuador", "Send request": "Enviar solicitud", "About the artist": "Sobre el artista", "Important information": "Información importante", "Selected work": "Trabajos seleccionados", "Before you send a request": "Antes de enviar una solicitud", "Artist requirements": "Requisitos del artista", "Start your tattoo project": "Inicia tu proyecto de tatuaje", "Artist profile unavailable": "Perfil no disponible", "This artist profile could not be found.": "No se encontró este perfil de tatuador.", "Explore studios": "Explorar estudios", "Loading artist profile...": "Cargando perfil...", "InkRoute will keep your request, consultation and tattoo sessions organized in one place.": "InkRoute organiza tu solicitud, consulta y sesiones de tatuaje en un solo lugar."
  },
  it: {
    "Send your idea directly to": "Invia la tua idea direttamente a",
    "Your public link": "Il tuo link pubblico", "Receive requests directly": "Ricevi richieste direttamente", "Send this link to a client or add it to your bio to receive structured requests directly in InkRoute.": "Invia questo link a un cliente o aggiungilo alla tua bio per ricevere richieste strutturate direttamente in InkRoute.", "Copy link": "Copia link", "Share": "Condividi", "Link copied": "Link copiato", "Tattoo artist": "Tatuatore", "Send request": "Invia richiesta", "About the artist": "Informazioni sull’artista", "Important information": "Informazioni importanti", "Selected work": "Lavori selezionati", "Before you send a request": "Prima di inviare una richiesta", "Artist requirements": "Requisiti dell’artista", "Start your tattoo project": "Inizia il tuo progetto tattoo", "Artist profile unavailable": "Profilo non disponibile", "This artist profile could not be found.": "Questo profilo tatuatore non è stato trovato.", "Explore studios": "Esplora gli studi", "Loading artist profile...": "Caricamento profilo...", "InkRoute will keep your request, consultation and tattoo sessions organized in one place.": "InkRoute organizza richiesta, consulenza e sessioni tattoo in un unico posto."
  }
};
